# YAML configuration for stageUtil
---

systemname: "SYSTEMNAME"
structure: {
    initial_pdb: "_init/b-Design/SYSTEMNAME.POSTPDB2PQR.pdb",
    topology:    ~,
    coordinates: ~,
}
engine: "AMBER"
parameterisation: {
    forcefields: {
        solute:  ["leaprc.protein.ff14SB"],
        solvent: ["leaprc.water.tip3p"],
        other:   ["leaprc.gaff2"],
    },
    water_model:   TIP3PBOX,
    water_padding: 12,  # add water to box until protein has at least 12 Å to the edge of the box
    ions: {
        Na+: 0,  # neutralise the box with sodium ions
        Cl-: 0,  # neutralise the box with chloride ions
    },
}
equilibration_protocols: [
    {
        stagename: "EQ-a-min",
        template:  "_init/c-Staging/_templates/_MD.Amber.EQ-a-min.conf",
    },
    {
        stagename: "EQ-b-heat",
        template:  "_init/c-Staging/_templates/_MD.Amber.EQ-b-heat.conf",
    },
    {
        stagename: "EQ-c-density",
        template:  "_init/c-Staging/_templates/_MD.Amber.EQ-c-density.conf",
    },
    {
        stagename: "EQ-d-equil",
        template:  "_init/c-Staging/_templates/_MD.Amber.EQ-d-equil.conf",
    }
]
simulation_protocol: {
    stagename:      "MD",
    template:       "_init/c-Staging/_templates/_MD.Amber.MD.conf",
    dt:             0.002,  # ps
    segment_length: 100,  # ns
    total_length:   1000,  # ns
}
