# YAML configuration for stageUtil
---

systemname: "FN3Con.alone"
structure: {
    initial_pdb: "../b-Design/FN3Con.complex.d-cyxnowat.pdb",
}
engine: "AMBER"
parameterisation: {
    forcefields: {
        solute:  ["leaprc.protein.ff14SB"],
        solvent: ["leaprc.water.tip3p"],
        other:   ["leaprc.gaff2"],
    },
    water_model:   TIP3PBOX,
    water_padding: 12,  # add water to box until protein has at least 12 Å to the edge of the box
    ions: {
        Na+: 0,  # neutralise the box with sodium ions
        Cl-: 0,  # neutralise the box with chloride ions
    },
}
equilibration_protocols: [
    {
        stagename: "EQ-a-min"
    },
    {
        stagename: "EQ-b-heat"
    },
    {
        stagename: "EQ-c-density"
    },
    {
        stagename: "EQ-d-equil"
    }
]
simulation_protocol: [
    {
        stagename: "MD"
    }
]

